### ISSUE TITLE
Add display of unsupported stepTypes in case of error

### ISSUE THREAD

**Issue by davidlinse** [sebuilder/se-builder#242]
When loading a (manually crafted) test which contains an unsupported ```stepType`` 
it would be pretty helpful to show the _name/type_ of the offending step.

Currently only the following infos were displayed.
```
Unable to read file, sorry.
Selenium 1: Unknown command in test script
Selenium 1 Suite: Failed to load test suite: <table> tag not found
Selenium 2: TypeError: this.type is undefined
Selenium 2 Suite: Could not open suite
```

regards
~david

**Comment by Zarkonnen** [comment]
What, you mean "TypeError: this.type is undefined" doesn't tell you everything you need to know?

Er, yes, good idea. :D

**Comment by davidlinse** [comment]
@Zarkonnen Sorry for bothering.. Any news on this ?

**Comment by Zarkonnen** [comment]
Court of the Squirrel Queen. Fixed now, new release coming very soon!
