### ISSUE TITLE
Adding a user extenison in se-builder

### ISSUE THREAD

**Issue by andy-palmer** [sebuilder/se-builder#247]
Is it possible to use user extensions (e.g. user-extension.js) in se-builder as you can in IDE?

We have read the information available on http://docs.seleniumhq.org/docs/08_user_extensions.jsp but this doesn't cover se-builder.

Any help?

**Comment by Zarkonnen** [comment]
Yes! It doesn't seem to be properly documented, but if you put a user-extensions.js into <your profile>/SeBuilder/, it should be recognized. Note that this only works for adding steps, not for the more IDE-specific stuff.

**Comment by andy-palmer** [comment]
I have had another look at this and have created a user-extensions.js in /SeBuilder/,

I have now realized what the problem is, User-extension only seem to be available in SE1.  Are there plans to make these available in SE2?
