### ISSUE TITLE
Se builder wont run test on FF 36

### ISSUE THREAD

**Issue by bowlej** [sebuilder/se-builder#249]
I have just updated my FF version on my mac workstation to 36.

I loaded the se-builder GUI and selected a test to run.

I selected 'Run tests locally' but the test did not run. 

I then started an instance of selenium server and selected 'Run on selenium server' the tests ran fine. 

Are other people seeing this issue?

I am using the latest version of selenium server. 

Firefox version 34 does work ok.

**Comment by teyamagu** [comment]
i see this issue.
i think this issue was caused by https://code.google.com/p/selenium/issues/detail?id=8399

**Comment by barancev** [comment]
See https://github.com/sebuilder/se-builder/pull/252

**Comment by Zarkonnen** [comment]
Confirmed bug, will now look at patch. Apologies for the slow response time, I was ~~summoned to the court of the Squirrel Queen~~ really busy.

**Comment by Zarkonnen** [comment]
Thanks to barancev's PR this is now fixed in HEAD and soon in 2.3.1.
